//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string UID { get; set; }
        public string NameAC { get; set; }
        public string CountryAC { get; set; }
        public string Status { get; set; }
        public string idSA { get; set; }
        public Nullable<int> idDevice { get; set; }
        public string passAC { get; set; }
        public string twoFA { get; set; }
        public string emailAC { get; set; }
        public string passEmail { get; set; }
    }
}
