//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD
    {
        public string id { get; set; }
        public string NameADS { get; set; }
        public string TypeADS { get; set; }
        public Nullable<bool> IsPersonal { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<int> Threshold { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> SpentAmount { get; set; }
        public Nullable<int> PaymentMethods { get; set; }
        public string idSA { get; set; }
        public Nullable<int> idAC { get; set; }
    }
}
