//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BM
    {
        public string id { get; set; }
        public string NameBM { get; set; }
        public Nullable<int> SharingStatus { get; set; }
        public Nullable<int> AdCreateLimit { get; set; }
        public Nullable<int> Verified { get; set; }
        public Nullable<int> PaymentMethods { get; set; }
        public string idSA { get; set; }
        public string iaAC { get; set; }
        public Nullable<int> idAC { get; set; }
    }
}
