//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataManagementEntities : DbContext
    {
        public DataManagementEntities()
            : base("name=DataManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AD> ADS { get; set; }
        public virtual DbSet<BM> BMs { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<GroupM> GroupMs { get; set; }
        public virtual DbSet<PageM> PageMs { get; set; }
        public virtual DbSet<Payout> Payouts { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<RoleSA> RoleSAs { get; set; }
        public virtual DbSet<StaffaAccount> StaffaAccounts { get; set; }
        public virtual DbSet<StaffAccount> StaffAccounts { get; set; }
    }
}
