//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int idDevice { get; set; }
        public string nameDevice { get; set; }
        public string serialnumber { get; set; }
        public string typeDevice { get; set; }
        public string idSA { get; set; }
    }
}
