//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupM
    {
        public string idG { get; set; }
        public string nameG { get; set; }
        public Nullable<int> MemCount { get; set; }
        public string countryG { get; set; }
        public string languageG { get; set; }
        public string Topic { get; set; }
        public string CHECKidSA { get; set; }
        public string idAC { get; set; }
    }
}
