//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageM
    {
        public string idP { get; set; }
        public string nameP { get; set; }
        public Nullable<int> FollowCount { get; set; }
        public Nullable<int> VideoCount { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<bool> Adbreak { get; set; }
        public Nullable<bool> Reel { get; set; }
        public Nullable<bool> Bonus { get; set; }
        public Nullable<bool> RightManager { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string countryP { get; set; }
        public string languageP { get; set; }
        public string Topic { get; set; }
        public string CHECKidSA { get; set; }
        public string idAC { get; set; }
    }
}
