//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payout
    {
        public string id { get; set; }
        public string NamePayout { get; set; }
        public string country { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string EarningSources { get; set; }
        public string CHECKidSA { get; set; }
        public Nullable<int> idAC { get; set; }
    }
}
