//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAccount
    {
        public string idSA { get; set; }
        public string UserSA { get; set; }
        public string NameSA { get; set; }
        public string PassWordSA { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<System.DateTime> cerated { get; set; }
        public string noteSA { get; set; }
    
        public virtual RoleSA RoleSA { get; set; }
        public virtual RoleSA RoleSA1 { get; set; }
    }
}
